# Generated by Django 6.0 on 2025-12-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_post_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('HISTORY', 'History'), ('CULTURE', 'Culture'), ('TRAVEL', 'Travel'), ('MY_LOG', 'My Log')], default='TRAVEL', max_length=20),
        ),
    ]
