name: Ops / Maintenance
description: 운영 점검/문서/커맨드/데이터 정합성 작업
title: "[ops] "
labels: ["ops", "phase:1"]
body:
  - type: textarea
    id: goal
    attributes:
      label: 목표
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: 범위/비범위
      description: 무엇을 포함/제외하는지
    validations:
      required: true

  - type: textarea
    id: checklist
    attributes:
      label: 체크리스트(성공 기준)
      placeholder: |
        - [ ]
        - [ ]
    validations:
      required: true

  - type: textarea
    id: rollback
    attributes:
      label: 롤백/복구 계획
    validations:
      required: true