# Generated by Django 6.0 on 2025-12-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='postimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
