# Generated by Django 6.0 on 2025-12-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='aliases',
            field=models.TextField(blank=True, default='', help_text='Globe 매칭용 별칭(콤마 구분). 예: South Korea, Korea, Republic of Korea'),
        ),
    ]
