# Generated by Django 6.0 on 2025-12-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_country_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_a2',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso_a3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='name_ko',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='aliases',
            field=models.TextField(blank=True, default=''),
        ),
    ]
