# Generated by Django 6.0 on 2025-12-24 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_seedmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSlugHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('old_slug', models.SlugField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_slug_history', to='blog.country')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_history', to='blog.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['country', 'category', 'old_slug'], name='blog_postsl_country_307055_idx')],
                'constraints': [models.UniqueConstraint(fields=('country', 'category', 'old_slug'), name='uniq_oldslug_per_country_cat')],
            },
        ),
    ]
