# Generated by Django 6.0 on 2026-01-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagSlugAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_aliases', to='blog.tag')),
            ],
            options={
                'indexes': [models.Index(fields=['old_slug'], name='blog_tagslu_old_slu_8c0981_idx')],
            },
        ),
    ]
